### ISSUE TITLE
 The 'token' parameter was found in the query string, but must be in the POST body 

### ISSUE THREAD

**Issue by CristianCantoro** [valhallasw/flask-mwoauth#15]
I'm writing an application that uses this module to make modification to a Wikipedia page. The title of the bug is the error message I get from the server.

The code making the request is as follows:
```python
edit_query = {'action': 'edit',
              'title': title.encode('utf-8'),
              'summary': summary.encode('utf-8'),
              'text': new_text.encode('utf-8'),
              'token': edit_token
              }

if section != '-1':
    edit_query['section'] = section

result = mwoauth.request(edit_query)
```
This code used to work previously (~ 1 year ago). 

I think that now all edit requests should be handled as long requests.

**Comment by ricordisamoa** [comment]
The following might work
```python
result = mwoauth.mwoauth.post(mwoauth.base_url + '/api.php?', data=edit_query).data
```

**Comment by CristianCantoro** [comment]
Thank you @ricordisamoa, it works like a charm.

Just a little addition, I add to add a parameter `'format': 'json'` to the request to get the response in json format.

```python
edit_query = {'action': 'edit',
              'title': title,
              'summary': summary,
              'text': new_text.encode('utf-8'),
              'token': edit_token,
              'format': 'json'
              }

if section != '-1':
    edit_query['section'] = section

# result = mwoauth.request(edit_query, force_long=True)
# result = mock_success()
result = mwoauth.mwoauth.post(mwoauth.base_url + '/api.php?',
                              data=edit_query
                              ).data
```

Maybe it is useful to add it to the documentation?

**Comment by valhallasw** [comment]
No, because that breaks the separation between layers. `mwoauth` is internal to flask_mwoauth, and should have been marked as such (`_mwoauth`).

Can you try the following: changing lines 142 and 143 of
https://github.com/valhallasw/flask-mwoauth/blob/master/flask_mwoauth/__init__.py#L142
from
```
            return self.mwoauth.post(url + "/api.php?" + urlencode(api_query),
                                     content_type="text/plain").data
```
to
```
            return self.mwoauth.post(url + "/api.php",
                                     data=api_query,
                                     content_type="text/plain").data
```
?

**Comment by CristianCantoro** [comment]
Hi @valhallasw , thank you for your reply.

I get the following error:
```
ValueError: Body contains parameters but Content-Type header was text/plain instead of
application/x-www-form-urlencoded
```
the [full traceback is on pastebin](http://pastebin.com/gtxL5a9p).

So I have modified [line 142-143](https://github.com/valhallasw/flask-mwoauth/blob/master/flask_mwoauth/__init__.py#L142) to: 

```python
            return self.mwoauth.post(
                url + "/api.php",
                data=urlencode(api_query),
                content_type="application/x-www-form-urlencoded"
                ).data
```
and now it works.

I modified the request in the app back to:
```python
        edit_query = {'action': 'edit',
                      'title': title,
                      'summary': summary,
                      'text': new_text.encode('utf-8'),
                      'token': edit_token,
                      'format': 'json'
                      }

        if section != '-1':
            edit_query['section'] = section

        result = mwoauth.request(edit_query)
```

I should point out that also this variant works:
```python
            return self.mwoauth.post(url + "/api.php", data=api_query).data
```
Which one (if any) is correct?

**Comment by valhallasw** [comment]
Whoops, sorry for not responding earlier. I think the latter variant is probably the best one. I'll try to test and release a new version tonight.

**Comment by valhallasw** [comment]
Thank you for your help, Cristian!
