### ISSUE TITLE
Consider using https://github.com/mediawiki-utilities/python-mwoauth as a backend

### ISSUE THREAD

**Issue by yuvipanda** [valhallasw/flask-mwoauth#17]
Deals with the JWT stuff nicely - gets you centralauth ids and stuff that work well with the 'authenticate only' workflows in OAuth. Plus one widely used implementation > 2 split ones!

**Comment by valhallasw** [comment]
This is a great idea, but I currently do not have the time to work on it. However, if anyone feels like working on it, I will gladly merge changes.
